### ISSUE TITLE
Add new line before namespace keyword

### ISSUE THREAD

**Issue by joseluisq** [bobsta63/netbeans-psr-formatting#11]
Actually it looks like :

![captura de pantalla 2016-11-03 a las 12 13 07](https://cloud.githubusercontent.com/assets/1700322/19976726/fcb164ae-a1be-11e6-878e-0c3ad7ac7f07.png)

This solves the issue :

![captura de pantalla 2016-11-03 a las 12 10 52](https://cloud.githubusercontent.com/assets/1700322/19976669/c041d63e-a1be-11e6-99b6-1d616b29d246.png)

**Comment by allebb** [comment]
Hey @joseluisq - As long as you're using the latest release (https://github.com/bobsta63/netbeans-psr-formatting/releases/tag/v1.0.2) this is already resolved buddy :)

Cheers for logging though, I'll close the issue. - Do you me know if you have further issues.

**Comment by joseluisq** [comment]
It appears that doesn't work 
I have the v1.0.2

**Comment by allebb** [comment]
Sorry - Re-reading your original issue, appears you _want_ a blank line **before** the namespace 

Maybe I'm wrong but this isn't PSR1/PSR2 recommendations? See this page: http://www.php-fig.org/psr/psr-2/

If you feel I'm incorrect please let me know but as far as I'm concerned it's working fine for me?

**Comment by joseluisq** [comment]
It appears that **new lines before namespaces** is not mandatory in PSR-2 specs..
http://www.php-fig.org/psr/psr-2/#3-namespace-and-use-declarations

Anyway, I still think that'll be an idea to consider 👍 
Thanks

**Comment by allebb** [comment]
Yeah, given that my package currently does make the auto-formatting of code look as per their valid example, I'd prefer to keep it as it now (namespace on a new line but not a blank line between the opening PHP tag and the namespace).

<img width="791" alt="screenshot 2016-11-03 19 40 56" src="https://cloud.githubusercontent.com/assets/767628/19982396/d881465a-a1fd-11e6-8194-01c76f65bb03.png">

Obviously, you can override as per your own requirements but I think it's probably better to keep consistent with their example screenshots.

If others want to comment/request me to change this I will otherwise, personally I feel this is the currently correct and don't intend to change.

**Comment by allebb** [comment]
Alternatively you could use my previous version that supported a blank line given the previous bug with NetBeans. https://github.com/bobsta63/netbeans-psr-formatting/releases/tag/v1.0.1

:)

**Comment by joseluisq** [comment]
Sure, consistence is the rule. I don't pretend to change your plugin in favor to 😄  
instead I think is would be a good option to consider only..

For example (this is only a particular preference):

``` php
<?php
namespace App\Http\Controllers;

use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    function hello()
    {
        dd('Hello!')
    }
}
```

Instead:

``` php
<?php

namespace App\Http\Controllers;

use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    function hello()
    {
        dd('Hello!')
    }
}
```
