### ISSUE TITLE
Small issue

### ISSUE THREAD

**Issue by Dries-Vandenneucker** [bobsta63/netbeans-psr-formatting#7]
"The latest release" in the readme doesn't point to the latest release. Should be 1.0.1

**Comment by allebb** [comment]
It does point to the correct one in the "master" branch... I'll re-release now though, I guess when I fixed it several weeks ago (https://github.com/bobsta63/netbeans-psr-formatting/commit/117c0e9f64d5db2944be0eef5156e802211cc3a2) I thought that most people would just use the rendered README (master branch version) file for linking to the latest download ;)

I'll get it sorted now.

Cheers,
Bobby

**Comment by allebb** [comment]
Fixed and pushed a new generic link to the 'Releases' page on GitHub to mitigate this happening again in future. I have re-tagged the release and confirmed that the changes are present in the latest release version of the README file too.

Fixed in: https://github.com/bobsta63/netbeans-psr-formatting/commit/146254cecbf0f862dcec8f5f959509a3ec3bb85e
